### ISSUE TITLE
ha版本55无法使用miio库无法下载 

### ISSUE THREAD

**Issue by ylcrow** [mac-zhou/homeassistant-mi-acpartner#3]
python-miio==0.0.11 无法安装

**Comment by hugozheng2017** [comment]
改为>=0.0.11呢，miio版本应该早更新了。

**Comment by 0xbw** [comment]
修改了一下，试试看 [82e239b](https://github.com/mac-zhou/homeassistant-mi-acpartner/commit/5d188e3cec0445fbceef576ac77884fba0a68207)
