### ISSUE TITLE
switch学码问题

### ISSUE THREAD

**Issue by Clermonder** [mac-zhou/homeassistant-mi-acpartner#4]
空调伴侣在ha里用learn功能时，相同的按键每次学的码都不一样，您遇到这个问题了吗？

**Comment by 0xbw** [comment]
可能是你空调使用的是混合码，请问你空调的品牌和型号？
另外，那么学习的码有用么？

**Comment by Clermonder** [comment]
我是海尔的模卡电视学码，遇到这种问题。
空调是科龙的，预设的就可以。
每次学的码都不一样，所以我试了10次然后选了其中一个概率比较大的，但是当我把学习的码录入后，点了很多次仍是不管用。
